baseURL = "https://mbrandhorst.com/"
languageCode = "en-us"
title = "Cinematographer Max Brandhorst"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = "UA-49575020-1"

[params]
    author = "Max Brandhorst"
    description = "DoP Max Brandhorst"
    githubUsername = "maxbrand"
    accent = "pink"
    showBorder = false
    backgroundColor = "#000000"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = false
    highlightStyle = "solarized-dark"
    highlightLanguages = []

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/projects/"
    name = "Projects"
    weight = 2

[[menu.main]]
    url = "/about/"
    name = "About me"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:max.brandhorst@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://instagram.com/maxbrandop/"
    name = "instagram"
    weight = 2

[[menu.icon]]
    url = "https://www.facebook.com/max.brandhorst"
    name = "facebook"
    weight = 3

