baseURL = "mbrandhorst.com/"
languageCode = "en-us"
title = "DoP Max Brandhorst-Satzkorn"
hugpcdtheme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Max Brandhorst"
    description = "Director of Photography"
    githubUsername = "maxbrand"
    accent = "white"
    showBorder = false
    backgroundColor = "Black"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/blog/"
    name = "Blog"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:max@mbrandhorst.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://instagram.com/maxbrandop/"
    name = "instagram"
    weight = 2